### ISSUE TITLE
Tool does not work when version higher than v46

### ISSUE THREAD

**Issue by Illumina-Todd** [forcedotcom/Data-Migration-Tool#14]
It looks like something about the describe sobject response is breaking the tool when version > 46.  The response is in the logs and it looks valid but after that response a java error occurs.

Here's the stack trace for v47.  I used the delete account sample which works for v46.

com.sforce.ws.ConnectionException: unable to find end tag at:  START_TAG seen ...</customSetting><deepCloneable>... @1:64986
	at com.sforce.ws.bind.TypeMapper.consumeEndTag(TypeMapper.java:437)
	at com.sforce.soap.partner.DescribeSObjectResult.load(DescribeSObjectResult.java:1345)
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:674)
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:556)
	at com.sforce.soap.partner.DescribeSObjectResponse_element.setResult(DescribeSObjectResponse_element.java:48)
	at com.sforce.soap.partner.DescribeSObjectResponse_element.loadFields1(DescribeSObjectResponse_element.java:107)
	at com.sforce.soap.partner.DescribeSObjectResponse_element.loadFields(DescribeSObjectResponse_element.java:83)
	at com.sforce.soap.partner.DescribeSObjectResponse_element.load(DescribeSObjectResponse_element.java:77)
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:674)
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:556)
	at com.sforce.ws.transport.SoapConnection.bind(SoapConnection.java:180)
	at com.sforce.ws.transport.SoapConnection.receive(SoapConnection.java:154)
	at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:99)
	at com.sforce.soap.partner.PartnerConnection.describeSObject(PartnerConnection.java:1492)
	at migrator.core.service.impl.MetadataServiceImpl.process(MetadataServiceImpl.java:95)
	at migrator.core.service.impl.MetadataServiceImpl.process(MetadataServiceImpl.java:80)
	at migrator.core.service.MetadataObjectHolder.init(MetadataObjectHolder.java:77)
	at migrator.core.sobject.MigrableLookupObject.setup(MigrableLookupObject.java:111)
	at migrator.core.sobject.MigrableMasterDetailObject.setup(MigrableMasterDetailObject.java:90)
	at migrator.core.sobject.MigrableMasterDetailObject.process(MigrableMasterDetailObject.java:72)
	at migrator.core.sobject.MigrableObjectFactory.migrate(MigrableObjectFactory.java:68)
	at migrator.module.client.DeleteAccounts.process(DeleteAccounts.java:52)
	at migrator.module.client.DeleteAccounts.main(DeleteAccounts.java:57)
com.sforce.ws.ConnectionException: unable to find end tag at:  START_TAG seen ...</customSetting><deepCloneable>... @1:70305
	at com.sforce.ws.bind.TypeMapper.consumeEndTag(TypeMapper.java:437)
	at com.sforce.soap.partner.DescribeSObjectResult.load(DescribeSObjectResult.java:1345)
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:674)
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:556)
	at com.sforce.soap.partner.DescribeSObjectResponse_element.setResult(DescribeSObjectResponse_element.java:48)
	at com.sforce.soap.partner.DescribeSObjectResponse_element.loadFields1(DescribeSObjectResponse_element.java:107)
	at com.sforce.soap.partner.DescribeSObjectResponse_element.loadFields(DescribeSObjectResponse_element.java:83)
	at com.sforce.soap.partner.DescribeSObjectResponse_element.load(DescribeSObjectResponse_element.java:77)
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:674)
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:556)
	at com.sforce.ws.transport.SoapConnection.bind(SoapConnection.java:180)
	at com.sforce.ws.transport.SoapConnection.receive(SoapConnection.java:154)
	at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:99)
	at com.sforce.soap.partner.PartnerConnection.describeSObject(PartnerConnection.java:1492)
	at migrator.core.service.impl.MetadataServiceImpl.process(MetadataServiceImpl.java:93)
	at migrator.core.service.MetadataObjectHolder.init(MetadataObjectHolder.java:87)
	at migrator.core.service.impl.MetadataCompareService.findCommonFields(MetadataCompareService.java:107)
	at migrator.core.service.impl.MetadataCompareService.findCommonFields(MetadataCompareService.java:95)
	at migrator.core.sobject.MigrableLookupObject.setup(MigrableLookupObject.java:113)
	at migrator.core.sobject.MigrableMasterDetailObject.setup(MigrableMasterDetailObject.java:90)
	at migrator.core.sobject.MigrableMasterDetailObject.process(MigrableMasterDetailObject.java:72)
	at migrator.core.sobject.MigrableObjectFactory.migrate(MigrableObjectFactory.java:68)
	at migrator.module.client.DeleteAccounts.process(DeleteAccounts.java:52)
	at migrator.module.client.DeleteAccounts.main(DeleteAccounts.java:57)
Exception in thread "main" java.lang.NullPointerException
	at migrator.core.service.impl.MetadataCompareService.findCommonFields(MetadataCompareService.java:112)
	at migrator.core.service.impl.MetadataCompareService.findCommonFields(MetadataCompareService.java:95)
	at migrator.core.sobject.MigrableLookupObject.setup(MigrableLookupObject.java:113)
	at migrator.core.sobject.MigrableMasterDetailObject.setup(MigrableMasterDetailObject.java:90)
	at migrator.core.sobject.MigrableMasterDetailObject.process(MigrableMasterDetailObject.java:72)
	at migrator.core.sobject.MigrableObjectFactory.migrate(MigrableObjectFactory.java:68)
	at migrator.module.client.DeleteAccounts.process(DeleteAccounts.java:52)
	at migrator.module.client.DeleteAccounts.main(DeleteAccounts.java:57)

**Comment by anoop-singh1** [comment]
I will try to upgrade the versioning. thanks
